alias aliasconfig='gedit ~/.bash_aliases'

alias upd='sudo apt update && sudo apt upgrade'
alias ips='ip -c -br a'
alias his='history|grep'
alias ls='exa'
alias ports='netstat -tulanp'
alias update='./update.sh'
alias plexstatus='sudo service plexmediaserver status'
alias plexstart='sudo service plexmediaserver start'
alias plexstop='sudo service plexmediaserver stop'
